site_name: platanus
site_url: https://sukeya.github.io/platanus/
repo_url: https://github.com/sukeya/platanus
edit_uri: blob/main/docs/
nav:
  - Home: index.md
  - Reference :
    - btree_set: reference/btree_set.md
    - btree_multiset: reference/btree_multiset.md
    - btree_map: reference/btree_map.md
    - btree_multimap: reference/btree_multimap.md
theme:
  name: material
  favicon: img/blog_logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - content.action.edit
    - toc.integrate
    - navigation.top
    - navigation.indexes
  palette:
  # Palette toggle for automatic mode
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to system preference
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.arithmatex:
      generic: true
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      type: iso_date
  - git-committers:
      repository: sukeya/sukeya.github.io
      branch: main
      token: !!python/object/apply:os.getenv ["MKDOCS_GIT_COMMITTERS_APIKEY"]
  - glightbox
  - search
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
