site_name: platanus
site_url: https://sukeya.github.io/platanus/
repo_url: https://github.com/sukeya/platanus
edit_uri: blob/main/docs/
nav:
  - Home: index.md
  - Reference :
    - btree_set: reference/btree_set.md
    - btree_multiset: reference/btree_multiset.md
    - btree_map: reference/btree_map.md
    - btree_multimap: reference/btree_multimap.md
theme: readthedocs