name: Deploy

on: pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Set up MkDocs
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/deploy_requirements.txt
      - name: Deploy
        env:
          MKDOCS_GIT_COMMITTERS_APIKEY: ${{ secrets.GITHUB_TOKEN }}
        run: mkdocs gh-deploy
