name: Test
run-name: Test
on: pull_request

jobs:
  gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up
        run: bash .github/scripts/setup.sh
      - name: Install gcc
        run: sudo apt install -y gcc
      - name: Build tests
        run: |
          cmake --preset test_gcc -B build/debug/gcc
          cmake --build build/debug/gcc
      - name: Run tests
        run: ctest --test-dir build/debug/gcc --output-on-failure

  clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up
        run: bash .github/scripts/setup.sh
      - name: Install llvm
        run: bash .github/scripts/install_llvm.sh
      - name: Build tests
        run: |
          cmake --preset test_clang -B build/debug/clang
          cmake --build build/debug/clang
      - name: Run tests
        run: ctest --test-dir build/debug/clang --output-on-failure

  clang_memory:
    # libstdc++ and libc++ have uninitialized variables,
    # so I skip this job temporarily.
    if: "false"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up
        run: bash .github/scripts/setup.sh
      - name: Install llvm
        run: bash .github/scripts/install_llvm.sh
      - name: Build tests
        run: |
          cmake --preset test_clang_memory -B build/debug/clang/memory
          cmake --build build/debug/clang/memory
      - name: Run tests
        run: ctest --test-dir build/debug/clang/memory --output-on-failure
